app/routes/admin.py
from datetime import datetime, timedelta
from functools import wraps
from flask import Blueprint, render_template, request, redirect, flash, url_for
from flask_login import current_user, login_required
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from pytz import utc
import logging  
from app.db.db_models import User, WeeklySchedule, TimeOffRequest
from app.db.db import db
from app.forms import AdminWeeklyScheduleForm, ApproveRejectForm, AdminUserForm
from app.utils import get_user_timezone

# Initialize logger
logger = logging.getLogger(__name__)

# Rate Limiter Configuration
limiter = Limiter(
        key_func=get_remote_address,
        default_limits=["200 per day", "50 per hour"]
        )

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated or current_user.role != 'admin':
            flash("Unauthorized", "danger")
            return redirect(url_for('web.dashboard'))
        return f(*args, **kwargs)
    return decorated_function

# Blueprint Configuration
admin = Blueprint('admin', __name__)

# ADMIN DASHBOARD ROUTE
@admin.route("/admin_dashboard", methods=["GET", "POST"])
@login_required
@admin_required
def admin_dashboard():
    
    # Initialize forms
    approve_reject_form = ApproveRejectForm()

    # Fetch users and schedules
    users = User.query.filter_by(role='user').order_by(User.first_name, User.last_name).all() # Sort by name
    all_users = User.query.order_by(User.role.asc(), User.first_name, User.last_name).all()
    # Only users have schedules, admins do not
    weekly_schedules = WeeklySchedule.query.join(User).filter(User.role == 'user').all()
    time_off_requests = TimeOffRequest.query.filter(TimeOffRequest.date >= datetime.today().date()).all() # Filter past dates

    # Calculate the current week's dates (Monday to Sunday)
    today = datetime.today()
    start_of_week = today - timedelta(days=today.weekday()) # Start on Monday
    week_dates = [(start_of_week + timedelta(days=i)) for i in range(7)]

    # Get the user's timezone
    viewer_tz = get_user_timezone()

    # Map schedules to users
    user_schedule_mapping = {}
    for user in users:
        user_schedule_mapping[user.id] = {}
        for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']:
            schedule = next((s for s in weekly_schedules if s.user_id == user.id and s.day_of_week == day), None)
            has_time_off = any(r for r in time_off_requests if r.user_id == user.id and r.date.strftime('%A') == day and r.status == 'approved')

            # Convert times to viewer's timezone
            try:
                if schedule and schedule.start_time:
                    schedule_start_datetime = datetime.combine(datetime.today(), schedule.start_time)
                    schedule.start_time = utc.localize(schedule_start_datetime).astimezone(viewer_tz).time()
                if schedule and schedule.end_time:
                    schedule_end_datetime = datetime.combine(datetime.today(), schedule.end_time)
                    schedule.end_time = utc.localize(schedule_end_datetime).astimezone(viewer_tz).time()
            except Exception as e:
                logger.error(f"Error converting schedule times for user {user.id} on {day}: {e}")
                flash(f"Error converting schedule times for user {user.id} on {day}.", "danger")

            user_schedule_mapping[user.id][day] = {
                'schedule': schedule,
                'has_time_off': has_time_off,
            }
    
    return render_template(
        "admin_dashboard.html",
        approve_reject_form=approve_reject_form,
        user_schedule_mapping=user_schedule_mapping,
        time_off_requests=time_off_requests,
        users=users,
        week_dates=week_dates,
        all_users=all_users
    )

# ADMIN: HANDLE TIME OFF ROUTE
@admin.route("/admin_dashboard/handle_time_off", methods=["POST"])
@login_required
@admin_required
def handle_time_off():

    approve_reject_form = ApproveRejectForm()

    logger.debug(f"Processing time-off request ID: {approve_reject_form.request_id.data}, Action: {approve_reject_form.action.data}")
    if approve_reject_form.validate_on_submit():
        request_id = approve_reject_form.request_id.data
        action = approve_reject_form.action.data

        try:
            time_off_request = TimeOffRequest.query.get(request_id)
            if not time_off_request:
                flash('Time off request not found.', 'error')
                return redirect(url_for('admin.admin_dashboard'))
            
            if action == 'approve':
                time_off_request.status = 'approved'
                flash('Time off request approved.', 'success')
            elif action == 'reject':
                time_off_request.status = 'rejected'
                flash('Time off request rejected.', 'danger')

            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.error(f"Error processing time-off request: {e}")
            flash('Error processing request.', 'error')
        return redirect(url_for('admin.admin_dashboard'))
    else:
        logger.error("Form validation failed.")
        for field, errors in approve_reject_form.errors.items():
            logger.error(f"Validation errors for {field}: {errors}")
            flash(f"Validation errors for {field}: {errors}", "danger")
        return redirect(url_for('admin.admin_dashboard'))

@admin.route("/admin_dashboard/update_user/<int:user_id>", methods=["GET", "POST"])
@login_required
@admin_required
def update_user(user_id):
    user = User.query.get_or_404(user_id)
    viewer_tz = get_user_timezone()

    if request.method == "GET":
        forms = {day: AdminWeeklyScheduleForm(prefix=f"{user_id}_{day}") for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']}

        schedules = {s.day_of_week: s for s in WeeklySchedule.query.filter_by(user_id=user_id).all()}
        for day, form in forms.items():
            form.day_of_week.data = day
            if day in schedules:
                schedule = schedules[day]

                try:
                    if schedule.start_time:
                        schedule_start_datetime = datetime.combine(datetime.today(), schedule.start_time)
                        form.start_time.data = utc.localize(schedule_start_datetime).astimezone(viewer_tz).time()
                    if schedule.end_time:
                        schedule_end_datetime = datetime.combine(datetime.today(), schedule.end_time)
                        form.end_time.data = utc.localize(schedule_end_datetime).astimezone(viewer_tz).time()
                except Exception as e:
                    logger.error(f"Error converting times for user {user_id} on {day}: {e}")
                    flash(f"Error displaying schedule times for {day}.", "danger")

                form.is_virtual.data = schedule.is_virtual
                form.is_unavailable.data = schedule.is_unavailable

        user_form = AdminUserForm(obj=user)
        return render_template("manage_user.html", user=user, user_form=user_form, forms=forms)

    # Determine which form was submitted
    form_type = request.form.get("form_type")

    if form_type == "user_form":
        user_form = AdminUserForm(obj=user)
        if user_form.validate_on_submit():
            old_role = user.role  # Store the previous role
            # Check if username or email is taken by another user
            existing_user = User.query.filter(
                (User.username == user_form.username.data) | (User.email == user_form.email.data) | (User.slack_username == user_form.slack_username.data),
                User.id != user.id
            ).first()
            if existing_user:
                flash('Username or email is already taken.', 'danger')
                return redirect(url_for("admin.update_user", user_id=user_id))

            user.first_name = user_form.first_name.data
            user.last_name = user_form.last_name.data
            user.username = user_form.username.data
            user.slack_username = user_form.slack_username.data
            user.email = user_form.email.data
            user.role = user_form.role.data

            if user_form.password.data:
                user.set_password(user_form.password.data)  # Reset password

            # If user is promoted to admin, delete their schedule
            if old_role != "admin" and user_form.role.data == "admin":
                WeeklySchedule.query.filter_by(user_id=user_id).delete()

            try:
                db.session.commit()
                flash("User details updated successfully.", "success")

                # Redirect to `manage_admin.html` if the user was promoted
                if user_form.role.data == "admin":
                    return redirect(url_for("admin.manage_admin", user_id=user_id))
                    
            except Exception as e:
                logger.error(f"Error updating user details for {user_id}: {e}")
                flash("An error occurred while updating user details.", "danger")

        return redirect(url_for("admin.update_user", user_id=user_id))

    elif form_type == "schedule_form":
        forms = {day: AdminWeeklyScheduleForm(prefix=f"{user_id}_{day}") for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']}
        
        for form in forms.values():
            form.process(formdata=request.form)

        if all(form.validate() for form in forms.values()):
            WeeklySchedule.query.filter_by(user_id=user_id).delete()

            for day, form in forms.items():
                is_unavailable = form.is_unavailable.data
                start_time_utc, end_time_utc = None, None

                if form.start_time.data and form.end_time.data and not is_unavailable:

app/templates/partials/admin/list_users.html
<!-- Users Grid/List Section -->
<h2 class="mt-4">Users
    <button id="toggleViewBtn" class="btn btn-outline-secondary" onclick="toggleView()" alt="Toggle View"
        title="Toggle View" type="button">
        <i id="toggleViewIcon" class="bi bi-layout-text-sidebar"></i>
    </button>
</h2>
<div class="card p-3 mb-4 shadow-sm">

    <!-- Grid View -->
    <div id="user-grid" class="row">
        {% for user in all_users %}
        <div class="col-md-3 col-sm-6">
            <div class="card shadow-sm mb-4">
                <div class="card-body text-center">
                    <div class="mb-3">
                        <img src="{{ get_gravatar_url(user.email) }}" alt="User Gravatar" class="rounded-circle"
                            width="80" height="80">
                    </div>
                    <h5 class="card-title mb-2">{{ user.first_name }} {{ user.last_name }}</h5>

                    <!-- Role Badge -->
                    {% if user.role == "admin" %}
                    <span class="badge bg-danger"><i class="bi bi-shield-lock me-1"></i> Admin</span>
                    {% else %}
                    <span class="badge bg-primary"><i class="bi bi-person me-1"></i> User</span>
                    {% endif %}
                    
                    {% if user.role == "admin" %}
                    <a href="{{ url_for('admin.manage_admin', user_id=user.id) }}"
                        class="btn btn-primary btn-sm w-100 mt-2">
                        <i class="bi bi-person-gear me-1"></i> Manage Admin
                    </a>
                    {% else %}
                    <a href="{{ url_for('admin.update_user', user_id=user.id) }}"
                        class="btn btn-primary btn-sm w-100 mt-2">
                        <i class="bi bi-person-gear me-1"></i> Manage User
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- List View -->
    <div id="user-list" class="d-none">
        <ul class="list-group shadow-sm">
            {% for user in all_users %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span>
                    <img src="{{ get_gravatar_url(user.email) }}" alt="User Gravatar" class="rounded-circle me-2"
                        width="40" height="40">
                    {{ user.first_name }} {{ user.last_name}}

                    <!-- Role Badge -->
                    {% if user.role == "admin" %}
                    <span class="badge bg-danger"><i class="bi bi-shield-lock me-1"></i> Admin</span>
                    {% else %}
                    <span class="badge bg-primary"><i class="bi bi-person me-1"></i> User</span>
                    {% endif %}
                </span>
                {% if user.role == "admin" %}
                <a href="{{ url_for('admin.manage_admin', user_id=user.id) }}" class="btn btn-primary btn-sm">
                    <i class="bi bi-person-gear me-1"></i> Manage Admin
                </a>
                {% else %}
                <a href="{{ url_for('admin.update_user', user_id=user.id) }}" class="btn btn-primary btn-sm">
                    <i class="bi bi-person-gear me-1"></i> Manage User
                </a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

app/templates/partials/admin/schedule_overview.html
<h2 class="mt-4">Weekly Schedule Overview</h2>
<div class="alert-important alert alert-info d-flex align-items-center py-2 px-3 mb-3 rounded-3 shadow-sm" role="alert">
    <i class="bi bi-globe2 me-2"></i> 
    <strong class="me-2">All times displayed in:</strong> {{ get_user_timezone() }}
</div>
<div class="card p-3 mb-4 shadow-sm">
    <div class="table-responsive">
        <table class="table table-bordered table-hover align-middle">
            <thead class="table-dark">
                <tr>
                    <th class="sticky-column"><i class="bi bi-person-fill"></i>Employee</th>
                    {% for day_date in week_dates %}
                    <th>
                        <i class="bi bi-calendar-week me-1"></i>
                        {{ day_date.strftime('%A') }}<br>
                        <small class="text-muted">{{ day_date.strftime('%b %d') }}</small>
                    </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td class="sticky-column text-center">
                        <div class="d-flex align-items-center justify-content-between">
                            <img src="{{ get_gravatar_url(user.email) }}" alt="User Gravatar" class="rounded-circle"
                                width="40" height="40">
                            <span class="ms-2">{{ user.first_name }} {{ user.last_name }}</span>
                        </div>
                    </td>
                    {% for day_name, day_data in user_schedule_mapping[user.id].items() %}
                    <td class="text-center">
                        {% if day_data.has_time_off %}
                        <span class="badge bg-warning text-dark" title="Day Off">
                            <i class="bi bi-sun me-1"></i>Day Off
                        </span>
                        {% elif day_data.schedule %}
                        {% if day_data.schedule.is_unavailable %}
                        <span class="badge bg-danger" title="Unavailable">
                            <i class="bi bi-x-circle me-1"></i>Unavailable
                        </span>
                        {% elif day_data.schedule.start_time and day_data.schedule.end_time %}
                        <div> <!-- This div ensures that badges are displayed underneath the times -->
                            {{ day_data.schedule.start_time.strftime('%H:%M %Z') }} - {{
                            day_data.schedule.end_time.strftime('%H:%M %Z') }}
                        </div>
                        {% if day_data.schedule.is_virtual %}
                        <span class="badge bg-info" title="Virtual Work">
                            <i class="bi bi-laptop me-1"></i>Virtual
                        </span>
                        {% endif %}
                        {% else %}
                        <span class="badge bg-secondary text-dark" title="No Schedule">
                            <i class="bi bi-slash-circle me-1"></i>No Schedule
                        </span>
                        {% endif %}
                        {% else %}
                        <span class="badge bg-secondary text-dark" title="No Schedule">
                            <i class="bi bi-slash-circle me-1"></i>No Schedule
                        </span>
                        {% endif %}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

app/templates/partials/admin/time_off.html
<h2 class="mt-4">Time Off Requests</h2>
<div class="card p-3 shadow-sm">
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th><i class="bi bi-person me-2"></i>Employee</th>
                    <th><i class="bi bi-calendar-event me-2"></i>Date</th>
                    <th><i class="bi bi-flag me-2"></i>Status</th>
                    <th><i class="bi bi-chat-text me-2"></i>Comment</th>
                    <th><i class="bi bi-gear me-2"></i>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for request in time_off_requests %}
                <tr>
                    <td>
                        <img src="{{ get_gravatar_url(request.user.email) }}" alt="User Gravatar"
                            class="rounded-circle me-2" width="40" height="40">
                        {{ request.user.first_name }} {{ request.user.last_name}}</td>
                    <td>{{ request.date }}</td>
                    <td class="text-center align-middle">
                        {% if request.status == 'pending' %}
                        <span class="badge bg-warning">
                            <i class="bi bi-hourglass-split me-1"></i>Pending</span>
                        {% elif request.status == 'approved' %}
                        <span class="badge bg-success">
                            <i class="bi bi-check-circle me-1"></i>Approved</span>
                        {% else %}
                        <span class="badge bg-danger">
                            <i class="bi bi-x-circle me-1"></i>Rejected</span>
                        {% endif %}
                    </td>
                    <td>{% if request.comment %}{{ request.comment }}{% else %}<i>No comment provided</i>{% endif %}</td>
                    <td class="text-center align-middle">
                        <div class="d-flex flex-column gap-2">
                            <form method="post" action="{{ url_for('admin.handle_time_off') }}" class="d-inline">
                                {{ approve_reject_form.csrf_token }}
                                {{ approve_reject_form.request_id(value=request.id) }}
                                {{ approve_reject_form.action(value='approve') }}
                                <button type="submit" class="btn btn-success btn-sm w-100" data-bs-toggle="tooltip"
                                    title="Approve Request">
                                    <i class="bi bi-check-circle me-1"></i> Approve
                                </button>
                            </form>
                            <form method="post" action="{{ url_for('admin.handle_time_off') }}" class="d-inline">
                                {{ approve_reject_form.csrf_token }}
                                {{ approve_reject_form.request_id(value=request.id) }}
                                {{ approve_reject_form.action(value='reject') }}
                                <button type="submit" class="btn btn-danger btn-sm w-100" data-bs-toggle="tooltip"
                                    title="Reject Request">
                                    <i class="bi bi-x-circle me-1"></i> Reject
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>